### ISSUE TITLE
New README

### ISSUE THREAD

**Issue by yschoen** [qkitgroup/qkit#14]
The README.md file is deprecated. Write new one with new and more information. Maybe similar to the MANUAL file in qtlab?
[MANUAL.txt](https://github.com/qkitgroup/qkit/files/1080733/MANUAL.txt)

**Comment by yschoen** [comment]
Maybe also VERSION and CHANGELOG?

**Comment by yschoen** [comment]
and INSTALL?

**Comment by rotzinger** [comment]
Maybe a real "doc" folder with content is useful. We could also put the examples there.
