### ISSUE TITLE
Link qviewkit.bat in install.bat

### ISSUE THREAD

**Issue by Schneider1** [qkitgroup/qkit#15]
In the install.bat add the functionality to register .h5 files with the qviewkit.bat.

Check that it works if and if not something is already registered with .h5

**Comment by mpfirrmann** [comment]
This might be done with sth. like this: 
[https://superuser.com/questions/29717/associate-a-file-type-with-a-specific-program](url)
`FTYPE h5_file=C:\qkit\qkit\gui\qviewkit\qviewkit.bat "%1"
ASSOC .h5=h5_file`

**Comment by rotzinger** [comment]
What is the status here? Can we close this?
