### ISSUE TITLE
VNA drivers

### ISSUE THREAD

**Issue by mpfirrmann** [qkitgroup/qkit#2]
Check VNA drivers for correct use of 
edel vs. port extension
estimating sweep time vs. trigger
set_Average

**Comment by Schneider1** [comment]
To enable the new spectroscopy script, all VNAs need the following functions:

`pre_measurement` is called once at the start
`start_measurement` is called every time, a new set of averages has to be taken (e.g. reset averages)
`ready` is queried every 0.2s and returns a Boolean
`post_measurement` brings the VNA back to a mode where it is usable by its frontend (e.g. not in hold mode)

**Comment by JBraumueller** [comment]
* set_Average is working now with Anritsu VNA MS4642B
* added parameter sweep_mode, replacing the hold function

These changes are comitted to the stable branch currently.

**Comment by rotzinger** [comment]
What is the status here? Can we close this?

**Comment by rotzinger** [comment]
There seems no hot interest anymore. Closing it.
