### ISSUE TITLE
Faulty X Axis Scaling in Qviewkit

### ISSUE THREAD

**Issue by fr34q** [qkitgroup/qkit#26]
When using logarithmical spaced values as x axis in a measurement (e.g. for a T1 measurement) the viewer interprets the x axis as lineary spaced thus leading to wrong axis labelling.

Example:
data0 > delay:
![image](https://user-images.githubusercontent.com/2014206/34905336-d521bbc4-f856-11e7-8786-4346b7e5e4a9.png)
(x axis is not really the delay but index)
This leads to a T1 measurement looking like:
data0 > phase_avg_0
![image](https://user-images.githubusercontent.com/2014206/34905344-fb907502-f856-11e7-8c87-c69486822937.png)
instead of an exponential decay

Expected behavior: When x axis is labelled "delay" it should also use the values given in the delay dataset and not extrapolate from only the first two data points or so.

**Comment by rotzinger** [comment]
Hi Richard,

this is most likely not a bug. Datasets in data0/analysis0 are displayed in Qviewkit as bare dataset with the x-axis being either None (just the index) or a optional x0+dx*N pair.  If you want to display a dataset vs a different axis  use the add_view() function in qkit.storage.store , which creates a view on the data.

Cheers, Hannes

**Comment by fr34q** [comment]
Hi Hannes,

shouldn't we then at least update the x axis labelling accordingly to avoid confusion? In my case, I expected to see an exponential decay and it took me a while to realize what was happening here because the x axis label was given as "delay (ns)".

But as we typically set the x axis explicitly I would find it more intuitive to use if the hdf data container would then contain these views automatically. Alternatively, a nice solution would be if one could specify an axis dataset for each individual dataset which is then used instead of linear spacing.

Your thoughts?

See you, Richard

**Comment by Schneider1** [comment]
Although considered to be not a bug, this behavior should have changed. Can you confirm that, Richard?

**Comment by fr34q** [comment]
Yes, as I said last week, this now works as I would expect it.

Delays for T1 measurement:
![screenshot](https://user-images.githubusercontent.com/2014206/53326845-d8a77f00-38e6-11e9-99ee-ee36f21579df.png)

Plot of the averaged phase:
![screenshot](https://user-images.githubusercontent.com/2014206/53326883-ee1ca900-38e6-11e9-8eb0-0d84b5e7c6d3.png)

So issue can stay closed ;)
