### ISSUE TITLE
Loding ri_client in qkit.__init__.py

### ISSUE THREAD

**Issue by Schneider1** [qkitgroup/qkit#30]
Currently, we load the ri_client in the qkit init, even if the user does not have zeropc installed or sets `qkit.cfg['load_ri_service'] = False`.
https://github.com/qkitgroup/qkit/blob/9daaebd9de3f869a9b668b9dad6ef0bf7bcbabe3/qkit/__init__.py#L40

**Comment by rotzinger** [comment]
Not a bug

**Comment by Schneider1** [comment]
> Qkit should start with the least possible dependencies. - HR

-> Bug.

**Comment by Schneider1** [comment]
Problem solved with b7bf6b82f389cd66288a940ce5f66465185bbabf
