### ISSUE TITLE
starting more qkit instances on the same pc

### ISSUE THREAD

**Issue by TimWolz** [qkitgroup/qkit#31]
It is only possible to open one qkit instance, i.e., qkit.start(), at the same time on the same pc. Otherwise a zmq error is prompted "address already in use". This is a problem for loading data via store.Data() if one works with several notebooks during data evaluation.

**Comment by rotzinger** [comment]
Two or more services open network ports, which can only be open once. FIX: A second instance of QKIT is  now trying to open the ports, but if this fails, it is not starting the service. 
Cheers, Hannes
