### ISSUE TITLE
wrong label on Qviewkit axes (several issues)

### ISSUE THREAD

**Issue by rotzinger** [qkitgroup/qkit#32]

**Comment by fr34q** [comment]
Related to #26

**Comment by rotzinger** [comment]
What is the status here?

**Comment by Schneider1** [comment]
For 1D plots, at least the problems in #26 should be fixed.

For 2D plots, the labels are still only valid for linear axes. The reason for that is that pyqtgraph uses something like `imshow` to draw the colorplots, which only supports equally spaced data points. AFAIK, there is not equivalent to `pcolormesh` in pyqtgraph and it's also not so easy to just relabel the axes.

**Comment by rotzinger** [comment]
This is indeed covered by #26, closing this issue.
