### ISSUE TITLE
change store_db to reg[ister|istry]

### ISSUE THREAD

**Issue by rotzinger** [qkitgroup/qkit#42]
I would like to suggest a name change in the core api:
change the qkit.store_db to something like qkit.reg  (short for register or registry)  since "store" is already taken and it would allow to unify the api. Comments?
The current store_db could be kept for a while.

**Comment by Schneider1** [comment]
What about measurement_db (or mdb)? Or maybe only `qkit.db`?

**Comment by rotzinger** [comment]
We settled this by introducing a new database object:
file info database
-----------------
which will be 
qkit.fid
=====
and is a merge of qkit.store_db and qkit.dbv. 
The new features are:
qkit.fid.show() -> opens a grided view on the database
qkit.fid.view(uuid,etc) -> opens qviewkit with the measurement file associated with uuid
changes:
all databases in qkit.fid have now the ending _db as in h5_db, h5_info_db, ...
apart from this, qkit.fid should replace qkit.store_db and qkit.dbv smothly.
Cheers, Hannes
