### ISSUE TITLE
cfg_local and cfg searched in config.local.py

### ISSUE THREAD

**Issue by Schneider1** [qkitgroup/qkit#45]
In our `qkit/__init__.py` we search for the following config arguments:

```
from qkit.config.local import cfg_local
# and later
from qkit.config.local import cfg as cfg_local
```
As we are only using the `cfg` variable in config.local, so I guess it should be fine to remove the `import cfg_local` part?

**Comment by rotzinger** [comment]
Well, no. In config/local.py there can be a definition of cfg = {} or cfg_local = {}. 
This depends how local.py was created. Originally local.py was a new file with the cfg_local = {} definition, we then introduced the possibility to just copy the environment.py into local.py and make changes there, which automatically means that cfg = {} is defined. 
So no action is needed.
