### ISSUE TITLE
Cannot run out of the box on Python 3.x

### ISSUE THREAD

**Issue by warrench** [qkitgroup/qkit#47]
Multiple modules contain errors which do not allow for the program to be run on a python 3.x distribution.

qkit.start() returns errors for print statements from 

- DatabaseViewer (Line 162, 167)
- hdf_view (Line 73, 84)

Fixed by enclosing print statements in parentheses

Syntax error in an exception statement in
hdf_view (Line 83)

Fixed by changing line to
`except SyntaxError as e`

**Comment by rotzinger** [comment]
Thank you for the report. The python 3.x is not very well tested, sorry.
The DatabaseViewer is going to be removed and replaced by a similar service "file info database (fid)" in a one of the coming commits so no need to fix this bug.
