### ISSUE TITLE
Circlefit

### ISSUE THREAD

**Issue by yschoen** [qkitgroup/qkit#53]
We should compare the newer version from Sebastian Probst with ours and decide if we want to replace ours.

Also many of us have in the past noticed some bugs or optimization potential in the circlefit. Maybe we could collect them here and see what should be changed and do that _after_ we switched to the new version from Sebastian.

**Comment by rotzinger** [comment]
We have a new maintainer for the circle fit, Dennis. I hope this solves the "lots of parallel" circle fits problem.
