### ISSUE TITLE
Traceback for spectroscopy measure 2D and 3D

### ISSUE THREAD

**Issue by TimWolz** [qkitgroup/qkit#55]
During 2D and 3D measurments in spectroscopy, probably also in measure_td and transport?, no full traceback is provided, which makes debugging absolutely tedious.
![grafik](https://user-images.githubusercontent.com/34345962/41289679-e3b0044c-6e4a-11e8-9c26-b9363819dea8.png)

**Comment by Schneider1** [comment]
This comes from the very crude `except Exception as e` in spectroscopy.py:644 https://github.com/qkitgroup/qkit/blob/da5c13d33cc488c24173cd8f8752ad10c0c29e6f/qkit/measure/spectroscopy/spectroscopy.py#L644

I suggest that the user should catch any error if he wants to run measurements in a loop and we simply remove the `except` block while maintaining the `finally` block.

**Comment by rotzinger** [comment]
Is this appropriately answered ?
