### ISSUE TITLE
beta testing branch

### ISSUE THREAD

**Issue by Schneider1** [qkitgroup/qkit#59]
Who is actively using the beta testing branch? And are there any open issues before we can merge beta-testing into master?

**Comment by yschoen** [comment]
Since qtlab-core and parametric pulses were merged separately, is this beta testing branch done or is there something else requiring testing?

**Comment by Schneider1** [comment]
There have been some other changes mainly in `qviewkit `and the `storage `lib.

Find the changes here: https://github.com/qkitgroup/qkit/pull/56/files
