### ISSUE TITLE
Automated plotting

### ISSUE THREAD

**Issue by mpfirrmann** [qkitgroup/qkit#66]
With the last qviewkit changes the automated plotting after a measurement shows incorrect tick labels. The index number instead of the value is labeled.

**Comment by rotzinger** [comment]
Micha, you worked on this. What is the status, is it resolved?

**Comment by Schneider1** [comment]
As far as I see, this issue is resolved, most probably with 60cb3b13dac76eb1abf53abb566bdde16a0c8124

If this issue continues to exist, please don't hesitate to re-open it
