### ISSUE TITLE
QFIT always outputs its config on instanciation

### ISSUE THREAD

**Issue by fr34q** [qkitgroup/qkit#70]
https://github.com/qkitgroup/qkit/blob/826f523efbb1f5f7d67da927910a0833628e7bfc/qkit/analysis/qfit.py#L111

I am using QFIT in headless mode in a script and would appreciate if this print statement can be turned off, e.g. if it would be conditional on some input parameter of the class (if it is necessary at all).

Any objections?

**Comment by JBraumueller** [comment]
No, please do! I also was about to make the unit conversion to GHz optional.
Will you edit the python 2.7 version only or also the one in the python 3 branch?

**Comment by fr34q** [comment]
@JBraumueller Done. I also think it's a good idea to use SI units by default.
